{% set version = "0.3.25" %}
{% set github = "https://github.com/hbc/bcbioRNASeq" %}

package:
  name: r-bcbiornaseq
  version: "{{ version }}"

source:
  url: "https://github.com/hbc/bcbioRNASeq/archive/v{{ version }}.tar.gz"
  sha256: c671989b72822ce2a983c3d2c227d811434bcf3af9a9830e9c36e3cc116a6f20

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base
    - bioconductor-summarizedexperiment >=1.14
    - r-basejump >=0.11.1
    # Imports:
    - bioconductor-biocgenerics >=0.30
    - bioconductor-degreport >=1.19.1
    - bioconductor-deseq2 >=1.22.1
    - bioconductor-edger >=3.26.5
    - bioconductor-genomicfeatures >=1.36
    - bioconductor-s4vectors >=0.22
    - bioconductor-tximport >=1.12.3
    - bioconductor-vsn >=3.52
    - r-acidplots >=0.2.7
    - r-bcbiobase >=0.6.7
    - r-bioverbs >=0.2.0
    - r-cowplot >=1.0
    - r-deseqanalysis >=0.2
    - r-dplyr >=0.8
    - r-ggplot2 >=3.2
    - r-ggrepel >=0.8
    - r-goalie >=0.2.19
    - r-knitr >=1.23
    - r-magrittr >=1.5
    - r-readr >=1.3
    - r-rlang >=0.4
    - r-scales >=1.0
    - r-sessioninfo >=1.1
    - r-stringr >=1.4
    - r-tibble >=2.1
    # Suggests:
    - bioconductor-biocparallel
    - bioconductor-biocstyle
    - bioconductor-clusterprofiler >=3.10.1
    - bioconductor-dose >=3.8
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-genomeinfodbdata
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-pathview >=1.22
    - bioconductor-rhdf5 >=2.28
    - r-hexbin >=1.27.3
    - r-pbapply >=1.4
    - r-rmarkdown >=1.0
    - r-tidyverse >=1.2.1
    - r-viridis >=0.5.1
  run:
    # Depends:
    - r-base
    - bioconductor-summarizedexperiment >=1.14
    - r-basejump >=0.11.2
    # Imports:
    - bioconductor-biocgenerics >=0.30
    - bioconductor-degreport >=1.19.1
    - bioconductor-deseq2 >=1.22.1
    - bioconductor-edger >=3.26.5
    - bioconductor-genomicfeatures >=1.36
    - bioconductor-s4vectors >=0.22
    - bioconductor-tximport >=1.12.3
    - bioconductor-vsn >=3.52
    - r-acidplots >=0.2.7
    - r-bcbiobase >=0.6.7
    - r-bioverbs >=0.2.0
    - r-cowplot >=1.0
    - r-deseqanalysis >=0.2
    - r-dplyr >=0.8
    - r-ggplot2 >=3.2
    - r-ggrepel >=0.8
    - r-goalie >=0.2.19
    - r-knitr >=1.23
    - r-magrittr >=1.5
    - r-readr >=1.3
    - r-rlang >=0.4
    - r-scales >=1.0
    - r-sessioninfo >=1.1
    - r-stringr >=1.4
    - r-tibble >=2.1
    # Suggests:
    - bioconductor-biocparallel
    - bioconductor-biocstyle
    - bioconductor-clusterprofiler >=3.10.1
    - bioconductor-dose >=3.8
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-genomeinfodbdata
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - bioconductor-pathview >=1.22
    - bioconductor-rhdf5 >=2.28
    - r-hexbin >=1.27.3
    - r-pbapply >=1.4
    - r-rmarkdown >=1.0
    - r-tidyverse >=1.2.1
    - r-viridis >=0.5.1

test:
  commands:
    - $R -e "library('bcbioRNASeq')"

about:
  home: http://bioinformatics.sph.harvard.edu/bcbioRNASeq/
  dev_url: "{{ github }}"
  license: MIT
  license_file: LICENSE
  summary: R package for bcbio RNA-seq analysis.
