{% set version = "1.5.1" %}
{% set sha256 = "7d9d401cf2b8ac4737ba0aadcb30c050462ca84262eda6a84fc00c5c230722df" %}

package:
  name: simka
  version: {{ version }} 

build:
  number: 0

source:
  url: https://github.com/GATB/simka/releases/download/v{{ version }}/simka-v{{ version }}-Source.tar.gz
  sha256: {{ sha256 }}
  patches:
    - "simkaMin.py.patch"
    - "simkaMin_update.py.patch"

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
  run:
    - zlib
    - python

test:
  commands:
    - simka -h
    - simkaMin.py --help

about:
  home: https://github.com/GATB/simka
  license: file
  license_file: LICENSE
  summary: Simka is a de novo comparative metagenomics tool. Simka represents each dataset as a k-mer spectrum and compute several classical ecological distances between them.
extra:
  identifiers:
    - biotools:Simka
    - doi:10.7717/peerj-cs.94
